###RECUPERAR TODAS LAS PELICULAS
GET http://localhost:1234/movies


###RECUPERAR LAS PELICULAS POR ID
GET http://localhost:1234/movies/1

###RECUPERAR LAS PELICULAS POR ID EXISTENETE
GET http://localhost:1234/movies/c8a7d63f-3b04-44d3-9d95-8782fd7dcfaf

###RECUPERAR TODAS LAS PELICULAS DE UN GENERO
GET http://localhost:1234/movies?genre=action

 
###HACER UN POST - CREAR UNA NUEVA PELICULA 
POST http://localhost:1234/movies
Content-Type: application/json

{
  "sql": "SELECT * FROM payments",
    "title": "The Lord of the Rings: The Fellowship of the Ring",
    "year": 2001,
    "director": "Peter Jackson",
    "duration":123,
    "genre": [
      "Adventure",
      "Drama",
      "Fantasy"
    ],
    "poster": "https://i.pinimg.com/originals/f1/43/69/f14369fb56e47283f02038b920654056.jpg",
    "rate": 8.5
}

###ELIMINAR UNA PELICULA
DELETE https://localhost/movies/dcdd0fad-a94c-4810-8acc-5f108d3b18c3

###HACER UN PATCH
PATCH http://localhost:1234/movies/8fb17ae1-bdfe-45e5-a871-4772d7e526b8 HTTP/1.1
Content-Type: application/json

{
  "year": 1901
}


###PREUEBA
GET https://api.themoviedb.org/3/authentication
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiI0YWUyYmVjYjM2MzNiNGM0YTcxMzg0NWE3YTE4ZTc1YyIsInN1YiI6IjY0Yzk1MTdiZDM3MTk3MDBjNWRlMDhmZSIsInNjb3BlcyI6WyJhcGlfcmVhZCJdLCJ2ZXJzaW9uIjoxfQ.4dPa3sB0GDIuiixWMlB-p43-i6GIVWshafX8UWiCvG4
Accept: application/json